"""修改客户电话长度限制20位

Revision ID: 3101a97994fc
Revises: 78ef0ea8c2a2
Create Date: 2026-03-27 11:12:34.893858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3101a97994fc'
down_revision: Union[str, Sequence[str], None] = '78ef0ea8c2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
